version: "3.7"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    volumes:
      - ./volumes/static/:/usr/src/app/static
      - ./volumes/media/:/usr/src/app/media
      - ./app/:/usr/src/app/
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    env_file: .env.db
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - ./volumes/static/:/usr/src/app/static
      - ./volumes/media/:/usr/src/app/media
    ports:
      - 80:80
    depends_on:
      - web
