version: "3.7"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./volumes/static/:/usr/src/app/static
      - ./volumes/media/:/usr/src/app/media
      - ./app/:/usr/src/app/
    ports:
      - 80:8000
    environment:
      - DEBUG=1
      - MODE=dev
