# Generated by Django 2.2.10 on 2021-04-16 11:31

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('surveys', '0004_question_question_type'),
        ('users', '0002_answer_response'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='UserResponse',
        ),
    ]
