# Generated by Django 2.2.10 on 2021-04-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210416_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='user_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='user unique identifier'),
        ),
    ]
