# Generated by Django 2.2.10 on 2022-04-08 13:51

import django.core.validators
from django.db import migrations, models
import surveys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checksum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('hash', models.CharField(db_index=True, max_length=128)),
                ('doc', models.FileField(upload_to=surveys.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
