# Generated by Django 2.2.10 on 2022-04-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checksum',
            old_name='name',
            new_name='author',
        ),
    ]
