# Generated by Django 2.2.10 on 2021-04-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_remove_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'text'), (2, 'radio'), (3, 'select')], default=1),
        ),
    ]
